### ISSUE TITLE
typescript unable to pick up definitions 

### ISSUE THREAD

**Issue by sam-soltech** [hodavidhara/griddle-react-typings#4]
I am using typescript 2.0 and i am unable to use these typings as the file naming is none-standard and is not in NPM of DefinitelyTyped. Is There a method to use installers to get valid type file?

**Comment by hodavidhara** [comment]
Yep! You can use https://github.com/typings/typings to install it pre-typescript 2.0 style. I'll try get around to getting it published to DefinitelyTyped so you can install it through npm and @types soon!

**Comment by dahlbyk** [comment]
This can be closed now: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15027

**Comment by hodavidhara** [comment]
Thanks again @dahlbyk !
